In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
a = np.array([[1], 
             [3]])
b = np.array([[1, -1],
              [6, 4]])
#apakah a adalah eigenfactor dari b? Jika iya, berapakah eigenvaluenya?

array([[ 1, -1],
       [ 6,  4]])

In [8]:
eig_val, eig_vec = np.linalg.eig(b)
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [9]:
eig_val

array([2.5+1.93649167j, 2.5-1.93649167j])