In [2]:
import numpy as np

In [34]:
from numpy.core.fromnumeric import take
#membuat tensor 
from numpy import array
t = array ([
            [[23,50], [7,12], [75,21], [57,12]],
            [[57,67], [99,43], [87,26], [18,84]]
])
print(t.shape)
t

(2, 4, 2)


array([[[23, 50],
        [ 7, 12],
        [75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43],
        [87, 26],
        [18, 84]]])

In [41]:
A = array ([
            [23, 50, 19],
            [7, 12, 109],
            [57, 67, 98]
])
print(A.shape)
A

(3, 3)


array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [24]:
B = array ([
            [17], 
            [22],
            [19]
])
print(B.shape)
B

(3, 1)


array([[17],
       [22],
       [19]])

In [25]:
#perkalian antara 2 A dot B karena aturan perkalian antara 2 vector sudah terpenuhi maka perkalian bisa berlangsung
A @ B

array([[1852],
       [2454],
       [4305]])

In [35]:
#transpose A
from numpy import array
transposeA = A.T
print(transposeA)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [42]:
#determinan A
from numpy import array
from numpy.linalg import det
A = array ([
            [23, 50, 19],
            [7, 12, 109],
            [57, 67, 98]
])
D = det(A)
print(D)

131344.0000000002


In [43]:
#inverse A
from numpy import array
from numpy.linalg import inv
A = array ([
            [23, 50, 19],
            [7, 12, 109],
            [57, 67, 98]
])
E = inv(A)
print(E)



[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
